name: Pull Request Build

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  pr-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-build') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Download dependencies
        run: |
          go install golang.org/x/tools/cmd/goyacc@latest
          go install gotest.tools/gotestsum@latest
          go install github.com/jandelgado/gcov2lcov@latest
          go install github.com/go-task/task/v3/cmd/task@latest

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: Convert coverage to lcov
        run: gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Verify that minium coverage is covered
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: "coverage.lcov"
          min_coverage: 50
